workdir: "Girrigatus"

organism: "Gliophorus irrigatus"

sra_ids:
- ERR13363478

hicpro_restriction_sites: "^GATC G^ANTC C^TNAG T^TAA"

hicpro_resolutions:
- 10000
- 20000
- 30000
- 40000
- 50000
- 100000

pastis_resolutions:
- 10000
- 20000
- 30000
- 40000
- 50000
- 100000

verify_contigs: True
