#!/usr/bin/env Rscript

# List of species names and those to be dropped to plot Figures 1 and 3
## just to make main scripts clearer

################################################################################
# All trees 

name_mapping <- c(
  "Abisporus" = "Agaricus bisporus",
  "Agentilis" = "Aureoboletus gentilis",
  "Aostoyae" = "Armillaria ostoyae",
  "Aperuvianus" = "Arachnomyces peruvianus",
  "Apraecox" = "Agrocybe praecox",
  "Arubescens" = "Amanita rubescens",
  "Bquercinus" = "Buglossoporus quercinus",
  "Bsubappendiculatus" = "Butyriboletus subappendiculatus",
  "Cbrunneum" = "Chlorophyllum brunneum",
  "Cfumosa" = "Clavaria fumosa",
  "Cfumosorosea" = "Cordyceps fumosorosea",
  "Cmicaceus" = "Coprinellus micaceus",
  "Cnorvegica" = "Cladonia norvegica",
  "Eclypeatum" = "Entoloma clypeatum",
  "Elanata" = "Ephebe lanata",
  "Eparvispora" = "Entomortierella parvispora",
  "Fmarina" = "Flavoplaca marina",
  "Fvelutipes" = "Flammulina velutipes",
  "Girrigatus" = "Gliophorus irrigatus",
  "Gresinaceum" = "Ganoderma resinaceum",
  "Hcoccinea" = "Hygrocybe coccinea",
  "Hcoralloides" = "Hericium coralloides",
  "Herinaceus" = "Hericium erinaceus",
  "Hpunicea" = "Hygrocybe punicea",
  "Igrammopodia" = "Inocybe grammopodia",
  "Iobscuroides" = "Inocybe obscuroides",
  "Itigrina" = "Inocybe tigrina",
  "Lblennius" = "Lactarius blennius",
  "Levosmus" = "Lactarius evosmus",
  "Lflavum" = "Leptographium flavum",
  "Llubrica" = "Leotia lubrica",
  "Lpygmaea" = "Lichina pygmaea",
  "Lsordida" = "Lepista sordida",
  "Lsulphureus" = "Laetiporus sulphureus",
  "Ltabidus" = "Lactarius tabidus",
  "Mgalericulata" = "Mycena galericulata",
  "Mzobellii" = "Metschnikowia zobellii",
  "Palboapiculata" = "Phaeoclavulina alboapiculata",
  "Pcalyptriformis" = "Porpolomopsis calyptriformis",
  "Pglauca" = "Platismatia glauca",
  "Postreatus" = "Pleurotus ostreatus",
  "Pstipticus" = "Panellus stipticus",
  "Ptriumphans" = "Phlegmacium triumphans",
  "Rcorniculata" = "Ramariopsis corniculata",
  "Rdelica" = "Russula delica",
  "Rfaginea" = "Russula faginea",
  "Rfarinipes" = "Russula aff farinipes",
  "Rirregularis" = "Rhizophagus irregularis",
  "Rkalkhoffii" = "Rhizosphaera kalkhoffii",
  "Rnigricans" = "Russula nigricans",
  "Rolivacea" = "Russula olivacea",
  "Rtricholoma" = "Ripartites tricholoma",
  "Rvesca" = "Russula vesca",
  "Slamellicola" = "Simplicillium lamellicola",
  "Sminoensis" = "Sparassis minoensis",
  "Tcingulatum" = "Tricholoma cingulatum",
  "Themisulphureum" = "Tricholoma hemisulphureum",
  "Tpullulans" = "Tausonia pullulans",
  "Udeusta" = "Umbilicaria deusta",
  "Vsurrecta" = "Volvariella surrecta",
  "Cmojavensis" = "Coemansia mojavensis",
  "Cobscurus" = "Conidiobolus obscurus",
  "Lpennispora" = "Linderina pennispora")

################################################################################
# Fig1

phyla <- c("Inocybe grammopodia" = "Basidiomycota",
           "Inocybe tigrina" = "Basidiomycota",
           "Phlegmacium triumphans" = "Basidiomycota",
           "Coprinellus micaceus" = "Basidiomycota",
           "Chlorophyllum brunneum" = "Basidiomycota",
           "Agaricus bisporus" = "Basidiomycota",
           "Amanita rubescens" = "Basidiomycota",
           "Volvariella surrecta" = "Basidiomycota",
           "Entoloma clypeatum" = "Basidiomycota",
           "Lepista sordida" = "Basidiomycota",
           "Tricholoma cingulatum" = "Basidiomycota",
           "Tricholoma hemisulphureum" = "Basidiomycota",
           "Armillaria ostoyae" = "Basidiomycota",
           "Flammulina velutipes" = "Basidiomycota",
           "Mycena galericulata" = "Basidiomycota",
           "Panellus stipticus" = "Basidiomycota",
           "Pleurotus ostreatus" = "Basidiomycota",
           "Gliophorus irrigatus" = "Basidiomycota",
           "Porpolomopsis calyptriformis" = "Basidiomycota",
           "Hygrocybe coccinea" = "Basidiomycota",
           "Hygrocybe punicea" = "Basidiomycota",
           "Clavaria fumosa" = "Basidiomycota",
           "Ramariopsis corniculata" = "Basidiomycota",
           "Aureoboletus gentilis" = "Basidiomycota",
           "Butyriboletus subappendiculatus" = "Basidiomycota",
           "Laetiporus sulphureus" = "Basidiomycota",
           "Sparassis minoensis" = "Basidiomycota",
           "Ganoderma resinaceum" = "Basidiomycota",
           "Hericium coralloides" = "Basidiomycota",
           "Lactarius blennius" = "Basidiomycota",
           "Lactarius tabidus" = "Basidiomycota",
           "Lactarius evosmus" = "Basidiomycota",
           "Russula delica" = "Basidiomycota",
           "Russula faginea" = "Basidiomycota",
           "Russula olivacea" = "Basidiomycota",
           "Russula nigricans" = "Basidiomycota",
           "Russula aff farinipes" = "Basidiomycota",
           "Russula vesca" = "Basidiomycota",
           "Phaeoclavulina alboapiculata" = "Basidiomycota",
           "Tausonia pullulans" = "Basidiomycota",
           "Arachnomyces peruvianus" = "Ascomycota",
           "Cladonia norvegica" = "Ascomycota",
           "Platismatia glauca" = "Ascomycota",
           "Flavoplaca marina" = "Ascomycota",
           "Umbilicaria deusta" = "Ascomycota",
           "Ephebe lanata" = "Ascomycota",
           "Lichina pygmaea" = "Ascomycota",
           "Cordyceps fumosorosea" = "Ascomycota",
           "Simplicillium lamellicola" = "Ascomycota",
           "Leptographium flavum" = "Ascomycota",
           "Leotia lubrica" = "Ascomycota",
           "Rhizosphaera kalkhoffii" = "Ascomycota",
           "Metschnikowia zobellii" = "Ascomycota",
           "Entomortierella parvispora" = "Mucoromycota",
           "Rhizophagus irregularis" = "Mucoromycota",
           "Coemansia mojavensis" = "Zoopagomycota",
           "Conidiobolus obscurus" = "Zoopagomycota",
           "Linderina pennispora"= "Zoopagomycota")

################################################################################
# Fig1 

map_colors <- c("Inocybe tigrina" = "#99CCCC",
                "Inocybe grammopodia" = "#115B75",
                "Phlegmacium triumphans" = "#9292b0",
                "Coprinellus micaceus" = "#115B75",
                "Chlorophyllum brunneum" = "#9292b0",
                "Agaricus bisporus" = "#115B75",
                "Volvariella surrecta" = "#9292b0",
                "Amanita rubescens" = "#08085E",
                "Tricholoma hemisulphureum" = "#9292b0",
                "Tricholoma cingulatum" = "#115B75",
                "Lepista sordida" = "#99CCCC",
                "Entoloma clypeatum" = "#9292b0",
                "Panellus stipticus" = "#115B75",
                "Mycena galericulata" = "#9292b0",
                "Flammulina velutipes" = "#115B75",
                "Armillaria ostoyae" = "#99CCCC",
                "Pleurotus ostreatus" = "#115B75",
                "Hygrocybe punicea" = "#9292b0",
                "Hygrocybe coccinea" = "#115B75",
                "Porpolomopsis calyptriformis" = "#9292b0",
                "Gliophorus irrigatus" = "#9292b0",
                "Ramariopsis corniculata" = "#115B75",
                "Clavaria fumosa" = "#99CCCC",
                "Butyriboletus subappendiculatus" = "#08085E",
                "Aureoboletus gentilis" = "#08085E",
                "Russula olivacea" = "#08085E",
                "Russula faginea" = "#115B75",
                "Russula nigricans" = "#08085E",
                "Russula vesca" = "#115B75",
                "Russula aff farinipes" = "#08085E",
                "Russula delica" = "#08085E",
                "Lactarius tabidus" = "#99CCCC",
                "Lactarius blennius" = "#115B75",
                "Lactarius evosmus" = "#08085E",
                "Hericium coralloides" = "#08085E",
                "Sparassis minoensis" = "#08085E",
                "Laetiporus sulphureus" = "#115B75",
                "Ganoderma resinaceum" = "#115B75",
                "Phaeoclavulina alboapiculata" = "#115B75",
                "Tausonia pullulans" = "#9292b0",
                "Platismatia glauca" = "#99CCCC",
                "Cladonia norvegica" = "#9292b0",
                "Flavoplaca marina" = "#115B75",
                "Umbilicaria deusta" = "#9292b0",
                "Arachnomyces peruvianus" = "#115B75",
                "Lichina pygmaea" = "#9292b0",
                "Ephebe lanata" = "#9292b0",
                "Simplicillium lamellicola" = "#99CCCC",
                "Cordyceps fumosorosea" = "#99CCCC",
                "Leptographium flavum" = "#115B75",
                "Leotia lubrica" = "#560A7F",
                "Rhizosphaera kalkhoffii" = "#990099",
                "Metschnikowia zobellii" = "#99CCCC",
                "Rhizophagus irregularis" = "#9292b0",
                "Entomortierella parvispora" = "#99CCCC",
                "Coemansia mojavensis" = NA,
                "Conidiobolus obscurus" = NA,
                "Linderina pennispora"= NA)

################################################################################
# Fig1 

map_shapes <- c("Inocybe tigrina" = 21,
                "Inocybe grammopodia" = 24,
                "Phlegmacium triumphans" = 24,
                "Coprinellus micaceus" = 24,
                "Chlorophyllum brunneum" = 24,
                "Agaricus bisporus" = 24,
                "Volvariella surrecta" = 24,
                "Amanita rubescens" = 21,
                "Tricholoma hemisulphureum" = 24,
                "Tricholoma cingulatum" = 24,
                "Lepista sordida" = 21,
                "Entoloma clypeatum" = 24,
                "Panellus stipticus" = 24,
                "Mycena galericulata" = 24,
                "Flammulina velutipes" = 24,
                "Armillaria ostoyae" = 21,
                "Pleurotus ostreatus" = 24,
                "Hygrocybe punicea" = 24,
                "Hygrocybe coccinea" = 24,
                "Porpolomopsis calyptriformis" = 24,
                "Gliophorus irrigatus" = 24,
                "Ramariopsis corniculata" = 24,
                "Clavaria fumosa" = 21,
                "Butyriboletus subappendiculatus" = 21,
                "Aureoboletus gentilis" = 21,
                "Russula olivacea" = 21,
                "Russula faginea" = 24,
                "Russula nigricans" = 21,
                "Russula vesca" = 24,
                "Russula aff farinipes" = 21,
                "Russula delica" = 21,
                "Lactarius tabidus" = 21,
                "Lactarius blennius" = 24,
                "Lactarius evosmus" = 21,
                "Hericium coralloides" = 21,
                "Sparassis minoensis" = 21,
                "Laetiporus sulphureus" = 24,
                "Ganoderma resinaceum" = 24,
                "Phaeoclavulina alboapiculata" = 24,
                "Tausonia pullulans" = 24,
                "Platismatia glauca" = 21,
                "Cladonia norvegica" = 24,
                "Flavoplaca marina" = 24,
                "Umbilicaria deusta" = 24,
                "Arachnomyces peruvianus" = 24,
                "Lichina pygmaea" = 24,
                "Ephebe lanata" = 24,
                "Simplicillium lamellicola" = 21,
                "Cordyceps fumosorosea" = 21,
                "Leptographium flavum" = 24,
                "Leotia lubrica" = 24,
                "Rhizosphaera kalkhoffii" = 21,
                "Metschnikowia zobellii" = 21,
                "Rhizophagus irregularis" = 24,
                "Entomortierella parvispora" = 21,
                "Coemansia mojavensis" = NA,
                "Conidiobolus obscurus" = NA,
                "Linderina pennispora"= NA)

################################################################################
# Fig1

dropped_tip_FullName <- c("Buglossoporus quercinus", "Hericium erinaceus", 
                 "Inocybe obscuroides", "Agrocybe praecox", 
                 "Ripartites tricholoma")

################################################################################
# Fig1
outgroupSpecies <- c("Lpennispora", "Cmojavensis", "Cobscurus")

################################################################################
# Fig2

dropped_species <- c("Bquercinus", "Herinaceus", "Iobscuroides", "Apraecox", 
                     "Rtricholoma")
################################################################################
# Fig1
map_tree <- c("Lpennispora", "Cmojavensis", "Cobscurus")

################################################################################
# Fig 2 and regressions figures

map_colorcode <- c(
  "Rabl" = "#99CCCC",
  "Bean shape" = "#08085E",
  "Chromosome Territories" = "#990099",
  "Rabl-Bean" = "#115B75", 
  "Bean-Chromosome Territories" = "#560A7F",
  "Chromosome Territories-Rabl" = "#9292b0"
)

################################################################################
# Fig3

reordered_tips <- c("Igrammopodia" = "Inocybe grammopodia",
                    "Vsurrecta" = "Volvariella surrecta",
                    "Postreatus" = "Pleurotus ostreatus",
                    "Girrigatus" = "Gliophorus irrigatus",
                    "Pcalyptriformis" = "Porpolomopsis calyptriformis",
                    "Hcoccinea" = "Hygrocybe coccinea",
                    "Cfumosa" = "Clavaria fumosa",
                    "Agentilis" = "Aureoboletus gentilis",
                    "Lsulphureus" = "Laetiporus sulphureus",
                    "Lblennius" = "Lactarius blennius",
                    "Ltabidus" = "Lactarius tabidus",
                    "Levosmus" = "Lactarius evosmus",
                    "Rdelica" = "Russula delica",
                    "Rnigricans" = "Russula nigricans",
                    "Rfarinipes" = "Russula aff farinipes",
                    "Rvesca" = "Russula vesca",
                    "Tpullulans" = "Tausonia pullulans",
                    "Cnorvegica" = "Cladonia norvegica",
                    "Lpygmaea" = "Lichina pygmaea",
                    "Cfumosorosea" = "Cordyceps fumosorosea",
                    "Slamellicola" = "Simplicillium lamellicola",
                    "Lflavum" = "Leptographium flavum",
                    "Rkalkhoffii" = "Rhizosphaera kalkhoffii",
                    "Mzobellii" = "Metschnikowia zobellii")